#include <string>

namespace Internal {

	//
	// Returns error descriptions as generated by Scrypt
	//
	std::string ScryptErrorDescr(const int error) {
		switch(error) {
			case 0:
				return "success";
			case 1:
				return "getrlimit or sysctl(hw.usermem) failed";
			case 2:
				return "clock_getres or clock_gettime failed";
			case 3:
				return "error computing derived key";
			case 4:
				return "could not read salt from /dev/urandom";
			case 5:
				return "error in OpenSSL";
			case 6:
				return "malloc failed";
			case 7:
				return "data is not a valid scrypt-encrypted block";
			case 8:
				return "unrecognized scrypt format";
			case 9:
				return "decrypting file would take too much memory";
			case 10:
				return "decrypting file would take too long";
			case 11:
				return "password is incorrect";
			case 12:
				return "error writing output file";
			case 13:
				return "error reading input file";
			default:
				return "error unkown";
		}

	} //end anon namespace
