#! /bin/sh
# Will run scrypt's autoconf generation script and save the output in the appropriate place

SCRIPTPATH=$(pwd)/scrypt/configuration
mkdir $SCRIPTPATH/config_output
cd $SCRIPTPATH/config_output && ../posix_configuration/configure -q 
cp /home/baz/Personal/Github/node-scrypt/scrypt/configuration/config_output/config.h $SCRIPTPATH/../config.h
rm -rf $SCRIPTPATH/config_output
