#! /bin/sh
# Will run scrypt's autoconf generation script

SCRIPTPATH="$(pwd)/scrypt/configuration"
if [ -d "$SCRIPTPATH/config_output" ]; then
    rm -rf "$SCRIPTPATH/config_output"
fi
mkdir "$SCRIPTPATH/config_output"
cd "$SCRIPTPATH/config_output" && "../posix_configuration/configure" -q
echo '@LIBS@' | "$SCRIPTPATH/config_output/config.status" --file=-
